name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Black
      run: nix develop --command black . --check --diff
    - name: Mypy
      run: nix develop --command mypy brew_tools
    - name: Pytest
      run: nix develop --command pytest
    - name: Build
      run: nix build
    - name: Flake check
      run: nix flake check

